_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1 # prevents early stopping
max_epochs: 10

# Use GPU and if available multiple GPUs
accelerator: "gpu"
devices: 1

# Enable mixed precision for extra speed-up
precision: 16

check_val_every_n_epoch: 1

deterministic: False
